spring.application.name=ILEIC-Gestion

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Helps keep the connection alive and identifies the DB type
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# This will create your tables automatically in Neon based on your Java classes
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION}

#fronendURL
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}